[project]
name = "stitches"
version = "0.1.0"
description = "A collection of animations using manim which show the patterns I follow when doing cross stitch"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "manim>=0.19.0",
]
